school/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('profile/', views.schoolProfile, name='schoolProfile'),

    path('admin_addSchool/', views.admin_addSchool, name='admin-AddSchool'),
    path('admin/allSchools/', views.admin_view_AllSchools, name='admin-view-AllSchools'),
    path('school/<int:id>/', views.admin_viewschool_detail, name='admin_viewschool_detail'),
    path('admin/edit/<int:pk>/school/', views.admin_edit_school, name='edit_school'),
    path('school/departments/<int:pk>/', views.admin_view_department, name='admin_view_department'),
    path('school/students/<int:pk>/', views.admin_students_by_school, name='admin_students_by_school'),
    path('school/department/<int:pk>/', views.admin_students_by_department, name='admin_students_by_category'),

    path('delete/<int:id>/', views.admin_School_Delete, name='admin-school-delete'),
    path('allStudents/', views.admin_view_students, name='admin-view-allStudents'),
    path('studentdue4payment/', views.admin_view_studentsdue4payment, name='adminview-studentdue4payment'),
    path('send_paymentconfirmation/', views.send_paymentconfirmationtostudent, name='send-paymentconfirmation'),

    # ====== SCHOOL URLS ====== #
    path('Add_Dept', views.school_addDept, name='addDept'),
    path('view_allDept', views.schoolview_allDept, name='view_allDept'),
    path('<int:id>', views.school_viewsdepartment_detail, name='view-Deptdetails'),
    path('department/edit/<int:pk>/', views.edit_Department, name='edit_department'),
    path('school_delete/<int:id>/', views.SchoolDelete_department, name='school-delete-department'),
    path('school_view/allStudents/', views.schoolview_allStudent, name='school-view-allStudents'),
    # path('department/deptchange-password/', login_required(SchoolChangePasswordView.as_view(), login_url='/login/'), name='Deptchange-password'),


    # ================== DEPARTMENT URLS ================== #
    path('department/addstudent/', views.dept_addstudent, name='department-addStudents'),
    path('department_view/allStudents/', views.deptview_allstudents, name='departmentview-allStudents'),
    path('department/<int:pk>', views.deptview_studentdetail, name='deptview-studentdetails'),
    path('dept_delete/<int:pk>/student/', views.deptDelete_student, name='department-delete-student'),
    path('department_edit/<int:pk>student/', views.deptedit_student, name='dept-editstudent'),


    path('department/profile/', views.departmentProfile, name='departmentProfile'),
    
  
]

sms_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('', include('authentication.urls')),
    
]

school/models.py
from django.db import models
from authentication.models import CustomUser

# Create your models here.


class School(models.Model):
    user = models.OneToOneField(CustomUser, related_name='user', on_delete=models.CASCADE)
    school_name = models.CharField(max_length=100)
    Address = models.TextField()
    mobile = models.CharField(max_length=15)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.school_name
    


class Department(models.Model):
    user = models.OneToOneField(CustomUser, related_name='dept_user', on_delete=models.CASCADE)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    department_name = models.CharField(max_length=50)
    department_code = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Department'
        verbose_name_plural = 'Departments'

    def clean(self):
        self.department_name = self.department_name.capitalize()
    
    def __str__(self):
        return self.department_name


class Student(models.Model):
    matric_no = models.CharField(max_length=15, unique=True)
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='student_department')
    bank_name = models.CharField(max_length=10)
    account_number = models.CharField(max_length=250, blank=True)
    mobile = models.CharField(max_length=15)
    email = models.EmailField(unique=True)
    payment_status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.matric_no +' ' + self.fname + ' ' + self.lname

sms/templates/sms/add_school.html
<div id="restaurant-sets-holder">
    <form action="{% url 'registerSchool' %}" class="form-fields-set foodbakery-dev-restaurant-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
            <li>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="row">
                            <ul >
                                <li>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="field-holder">
                                            <label>School Admin First name</label>{{user_form.first_name}}
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="field-holder">
                                            <label>School Admin Last name</label>{{user_form.last_name}}
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="field-holder">
                                            <label>School name</label>{{school_form.school_name}}
                                        </div>
                                    </div>
                                    <br>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="field-holder">
                                            <label>School Address</label>{{school_form.address}}
                                        </div>
                                    </div>

                                    <br>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="field-holder">
                                            <label>School Mobile No</label>{{school_form.mobile}}
                                        </div>
                                    </div>

                                    
                                    
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="field-holder">
                                            <label>School Admin Email Address</label>{{user_form.email}}
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="field-holder">
                                            <label>Username</label>{{user_form.username}}
                                        </div>
                                    </div>
                                </li>
                                
                                <li>
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                        <div class="field-holder">
                                            <label>Password</label>
                                            {{user_form.password}}
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                        <div class="field-holder">
                                            <label>Confirm Password</label>
                                            {{user_form.confirm_password}}
                                        </div>
                                    </div>
                                </li>
                            </ul>

                            
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <ul class="errorlist">
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <li style="color: red;">{{error}}</li>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}

                    <li style="color: red;">{{form.non_field_errors}}</li>
                </ul>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="field-holder">
                            <div class="payment-holder">
                                <input type="submit" value="Submit" id="btn-next-restaurant-information" class="bgcolor">
                            </div>
                        </div>
                    </div>
                </div>

            </li>
        </ul>
    </form>
</div>

sms/templates/sms/admin_view_allschools.html
{% extends 'sms/adminbase.html' %}



{% block content %}

<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
    </style>
    </head>
    <body>
    
    <h2>ALL SCHOOLS</h2>
    
    <table>
      <tr>
        <th>Serial</th>
        <th>School Name</th>
        <th>Email</th>
        <th>No of Department</th>
        {% comment %} <th>No of Students</th> {% endcomment %}
        <th>Actions</th>
      </tr>
      {% for school in all_schools %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'school-detail' school.id %}">{{ school.school_name }}</a></td>
        <td>{{ school.email }}</td>
        <td>{{ school.no_of_department }}
          {% comment %} <td>{{ school.no_of_students }}</td> {{ school.student_set.count }} {% endcomment %}
        <td><a href="#">Edit</a> 
            <a style="color: red;" href="{% url 'school-delete' school.id %}">Delete</a></td>
      </tr>
      {% endfor %}
    </table>
    
    
{% endblock %}

sms/templates/sms/school_detail.html
{% extends 'sms/adminbase.html' %}



{% block content %}

<meta charset="utf-8">


  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <style type="text/css">
    a:link {
      text-decoration: none;
    }

    .order-card {
      color: #fff;
    }

    .bg-c-blue {
      background: linear-gradient(45deg, #4099ff,#4a5c64);
    }

    .bg-c-green {
      background: linear-gradient(45deg, #2ed8b6, #4a5c64);
    }

    .bg-c-yellow {
      background: linear-gradient(45deg, #FFB64D, #4a5c64);
    }

    .bg-c-pink {
      background: linear-gradient(45deg, #30a33a, #4a5c64);
    }


    .card {
      border-radius: 5px;
      -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
      box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
      border: none;
      margin-bottom: 30px;
      -webkit-transition: all 0.3s ease-in-out;
      transition: all 0.3s ease-in-out;
    }

    .card .card-block {
      padding: 25px;
    }

    .order-card i {
      font-size: 26px;
    }

    .f-left {
      float: left;
    }

    .f-right {
      float: right;
    }

    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }
      
      tr:nth-child(even) {
        background-color: #dddddd;
      }
  </style>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
 
<div class="container">

    <h1>{{ school.school_name }}</h1>
    <div class="row">
      <div class="col-md-4 col-xl-4">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20">Number of Department</h6>
            <h2 class="text-right"><i class="fas fa-chalkboard-teacher f-left"></i><span>{{departments}}</span></h2>
            <!-- <p class="m-b-0">Pending Teacher<span class="f-right">{{pendingteachercount}}</span></p> -->
          </div>
        </div>
      </div>

      <div class="col-md-4 col-xl-4">
        <div class="card bg-c-green order-card">
          <div class="card-block">
            <h6 class="m-b-20">Total Student</h6>
            <h2 class="text-right"><i class="fas fa-user-graduate f-left"></i><span>{{students}}</span></h2>
            <!-- <p class="m-b-0">Pending Students<span class="f-right">{{pendingstudentcount}}</span></p> -->
          </div>
        </div>
      </div>

      <a href="#" class="col-md-4 col-xl-2" data-toggle="modal" data-target="#AddFilesModel" style="border-radius:5px;" class="btn-added">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20">Add Dept</h6>
            <h2 class="text-right"><i class="fas fa-building f-left"></i><span class="f-right">{{pendingschoolcount}}</span></h2>
            <!-- <p class="m-b-0">Pending Teacher</p> -->
          </div>
        </div>
      </a>

      <div class="col-md-4 col-xl-2">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20">Add Student</h6>
            <h2 class="text-right"><i class="fas fa-user-plus f-left"></i><span class="f-right">{{pendingschoolcount}}</span></h2>
            <!-- <p class="m-b-0">Pending Teacher</p> -->
          </div>
        </div>
      </div>

    </div>

    <br>



<ul class="menu-list">
    
</ul>
    
    <h2>School Department(s)</h2>
    
    <table>
      <tr>
        <th>Serial</th>
        <th>Department Name</th>
        <th>Department Code</th>
        <th>Department Email</th>
        <th>No of Students</th>
        <th>Actions</th>
      </tr>
      {% for department in school_departments %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ department.dept_name }}</td>
        <td>{{ department.dept_code }}</td>
        <td>{{ department.email }}</td>
        <td>{{ department.no_of_students }}</td>
        <td><a href="#">Edit</a> 
            <a href="#" style="color: red;">Delete</a></td>
      </tr>
      {% endfor %}
    </table>




        <!-- Add Department Bootstrap Modal -->
        <div class="modal fade" id="AddFilesModel" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add Department to This School</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="restaurant-sets-holder">
                        <form action="{% url 'school-detail' school.id %}" method="post">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                <ul >
                                                    <li>
                                                        <div class="col-md-12">
                                                            <div class="field-holder">
                                                                <label>Department HOD First name: </label>{{user_form.first_name}}
                                                            </div>
                                                        </div>
                                                        <br>
                                                        <div class="col-md-12">
                                                            <div class="field-holder">
                                                                <label>Department HOD Last name: </label>{{user_form.last_name}}
                                                            </div>
                                                        </div>
                                                        <br>
                                                        <div class="col-md-12">
                                                            <div class="field-holder">
                                                                <label>Department Name: </label>{{department_form.dept_name}}
                                                            </div>
                                                        </div>
                                                        <br>
                                                        <div class="col-md-12">
                                                            <div class="field-holder">
                                                                <label>Department Code</label>{{department_form.dept_code}}
                                                            </div>
                                                        </div>
                
                                                        <br>
                                                        <div class="col-md-12">
                                                            <div class="field-holder">
                                                                <label>Department Email Address: </label>{{department_form.email}}
                                                            </div>
                                                        </div>
                    
                                                        <br>
                                                        <br>
                                                        <div class="col-md-12">
                                                            <div class="field-holder">
                                                                <label>Username: </label>{{user_form.username}}
                                                            </div>
                                                        </div>
                                                    </li>
                                                    
                                                    <li>
                                                        <div class="col-md-6-12">
                                                            <div class="field-holder">
                                                                <label>Password: </label>
                                                                {{user_form.password}}
                                                            </div>
                                                        </div>
                                                        <div class="col-md-12">
                                                            <div class="field-holder">
                                                                <label>Confirm Password</label>
                                                                {{user_form.confirm_password}}
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                    
                                                
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <ul class="errorlist">
                                        {% for field in form %}
                                            {% if field.errors %}
                                                {% for error in field.errors %}
                                                    <li style="color: red;">{{error}}</li>
                                                {% endfor %}
                                            {% endif %}
                                        {% endfor %}
                    
                                        <li style="color: red;">{{form.non_field_errors}}</li>
                                    </ul>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Submit" id="btn-next-restaurant-information" class="btn btn-success">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                    
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>


  </div>

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
{% endblock %}